# Generated by Django 6.0.3 on 2026-04-01 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_buyerprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHGCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('primary_livelihood', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('silhouette_score', models.FloatField(default=0.5755)),
                ('db_index', models.FloatField(default=0.3707)),
                ('algorithm', models.CharField(default='K-Means', max_length=50)),
                ('k_value', models.IntegerField(default=10)),
                ('total_shgs', models.IntegerField(default=0)),
                ('avg_members', models.FloatField(default=0)),
                ('avg_savings', models.FloatField(default=0)),
                ('total_capacity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SHGClusterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shg_code', models.CharField(max_length=50)),
                ('shg_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('primary_livelihood', models.CharField(max_length=100)),
                ('secondary_livelihood', models.CharField(blank=True, max_length=100)),
                ('active_members', models.IntegerField(default=0)),
                ('savings_amount', models.FloatField(default=0)),
                ('shg_category', models.CharField(blank=True, max_length=20)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clusters.shgcluster')),
                ('shg_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_membership', to='users.shgprofile')),
            ],
            options={
                'ordering': ['cluster', 'state', 'district'],
            },
        ),
    ]
