# Generated by Django 6.0.3 on 2026-06-17 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
        ('products', '0003_alter_product_options_product_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('livelihood', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField()),
                ('fulfilled_quantity', models.IntegerField(default=0)),
                ('mode', models.CharField(choices=[('direct', 'Direct Allocation'), ('proportional', 'Proportional Allocation')], max_length=20)),
                ('partner_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_orders', to=settings.AUTH_USER_MODEL)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_orders', to='clusters.shgcluster')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_orders', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusterOrderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shg_name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(default=0)),
                ('allocated_quantity', models.IntegerField(default=0)),
                ('share_pct', models.FloatField(default=0)),
                ('cluster_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='clusters.clusterorder')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_allocations', to='clusters.shgclustermember')),
            ],
            options={
                'ordering': ['-allocated_quantity'],
            },
        ),
    ]
