# Generated by Django 6.0.3 on 2026-06-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_clusterorder_clusterorderallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterorderallocation',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_allocations', to='clusters.shgclustermember'),
        ),
    ]
