# Generated by Django 6.0.3 on 2026-03-21 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shg_orderitem_review_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='shg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_shg', to=settings.AUTH_USER_MODEL),
        ),
    ]
