# Generated by Django 6.0.3 on 2026-03-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerprofile',
            old_name='company_name',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='state',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shgprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shgprofile',
            name='members_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shgprofile',
            name='product_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shgprofile',
            name='production_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
