# Generated by Django 6.0.3 on 2026-03-21 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_company_name_buyerprofile_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_avatars/'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='email_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='email_recommendations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='price_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='ifsc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shg_logos/'),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shgprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shgprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shgprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shgprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
